### ISSUE TITLE
Chatbot Question Suggestion

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/chatbot#2]
I'd love to see suggestions on how to structure the questions that can be asked by the bot about generating a valid asyncapi document

**Comment by AceTheCreator** [comment]
`{
  "info": {
      "text": "Are you ready to generate your documentation?",
      "required": true,
      "q1":{
          "text": "what's the name of your spec?",
          "type": "string",
          "required": true
      },
      "q2":{
          "text": "what's the version of your spec?",
          "type": "number",
          "required": true
      },
      "q3":{
          "text": "what do you want to describe?",
          "type": "string",
          "required": false
      }
  },
  "servers":{
      "text":"What would you like to describe?",
      "required": false,
      "q1":{
        "text": "can you provide a server url for your server?",
        "required": false,
        "type": "string"
      },
      "q2":{
        "text": "can you provide more details about your server? Like what your server is for?",
        "required": false,
        "type": "string"
      }
  },
  "messages":{
      "text": "Is your app consuming or producing any messages?",
      "required": false,
      "canLoop": true,
      "q1": {
          "text": "what is the name of your first message?",
          "required": true,
          "type": "string"
      },
      "q2": {
          "text": "please paste the schema of your message in JSON format",
          "required": true,
          "type": "json"
      }
  },
  "channels": {
    "text": "Are you ready to tell me what topics/channels to send or read messages from?",
    "required": false,
    "canLoop": true,
    "q1": {
      "text": "what is the name of the channel/topic?",
      "required": true,
      "type": "string"
    },
    "q2": {
      "text": "what messages do you send there, provide names comma seperated",
      "required": false,
      "type": "array"
    },
    "q3": {
      "text": "do you read some messages from this channel too?",
      "required": false,
      "type": "array"
    }
  }
}`

Current list of questions and structuring available right now

**Comment by AceTheCreator** [comment]
@derberg any suggestions from your end?

**Comment by derberg** [comment]
lgtm, just few comments:

- `what's the name of your spec?` -> `what's the name of your application?`
- `what's the version of your spec?` -> `what's the version of your application?`
- `what do you want to describe?` -> `how would you describe your application? What is its purpose?`
- `What would you like to describe?` -> `Let's describe where is your application available? where to connect to get and send messages?`
- `can you provide a server URL for your server?` -> `can you provide a URL of your server?`
- `can you provide more details about your server? Like what your server is for?` - what is this question for? I think it is more important to ask that protocol is the server using, like mqtt or other
- `Is your app consuming or producing any messages?` -> `Would you like to specify what messages is your application producing or consuming?`
- in case of `channels` q2 and q3, that `type` means there, as I think we accept `string` with commas and them parse into `array`. Also we will need a way to display names of messages that user already provided to the chatbot, like asking q2 and q3 with info what messages user provided already, so picking the name is easy (long term would be awesome to show them as a list of buttons that user just need to click to mark)

**Comment by derberg** [comment]
@AceTheCreator do we still need this issue?

**Comment by AceTheCreator** [comment]
@derberg No. I'm closing it now
