### ISSUE TITLE
We Need Suggestions On First Bot Message For Engagement

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/chatbot#6]
Hello 👋. We need suggestions on how Lukasz's (it's the name of the chatbot) first engagement message should be 🙏🏻.

Lukasz just currently introduces himself by saying `Hello I'm Lukasz, I can help you out writing an AsyncAPI document. Try me!.` So I need suggestions on how Lukasz can make the user engage with him.

Our initial suggestion is Lukasz should ask the user `Would you love to generate an asyncapi document or you wanna ask a question about asyncapi?`

**Comment by magicmatatjahu** [comment]
Hi! Do we really wanna name the chatbot as Łukasz? 🤣  You can ask for your question it in our slack - a more people will se this issue. 

Your suggestion for me is good as opening message :)

**Comment by dsingh003** [comment]
Hi! I’m BotCore. I can help you out writing an AsyncAPI document. Try me!.

**Comment by AceTheCreator** [comment]
> Hi! I’m BotCore. I can help you out writing an AsyncAPI document. Try me!.

@dsingh003 Thanks for the suggestion, but we wanna name the bot Lukasz :+1:

**Comment by AceTheCreator** [comment]
> Hi! Do we really wanna name the chatbot as Łukasz?  You can ask for your question it in our slack - a more people will se this issue.
> 
> Your suggestion for me is good as opening message :)

Yeah we wanna name the bot Lukasz to make Lukasz jealous 🤣

**Comment by derberg** [comment]
Slowly replacing me, so I can just sit and do nothing 💪🏼 🙇🏼 🍺 

Good opening message, not sure about bot name though 😄

**Comment by derberg** [comment]
@AceTheCreator this one is already done right?

**Comment by magicmatatjahu** [comment]
@AceTheCreator bump 😄 . Is it still valid?

**Comment by AceTheCreator** [comment]
@magicmatatjahu Nope!

**Comment by magicmatatjahu** [comment]
@AceTheCreator Thanks for response! So I will close it :)
